### ISSUE TITLE
Passing Route 22 | causes exception

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#12]
**Route 22 Problem:**
Passing Route 22 is not possible. This happened to me on multiple occasions, when trying to get from Kanto to:
- Mt Silver
- Johto
- Kanto ViktoryRoad

When attempted following looping (exemplarary) exception will be printed:
>     ...
>     [17:01:39] Path: Maps Remains: 4 Moving To: --> Pokemon League Reception Gate
>     [17:01:39] Pathfinder --> Error in Path: from Route 22 to Pokemon League Reception Gate -- Reset and Recalc
>     [17:01:40] Path: Route 22->Pokemon League Reception Gate->Victory Road Kanto 1F->Victory Road Kanto 2F_A->Victory Road Kanto 3F_D
>     ...

Routing is fine, when Route 22 is selected as destiny or start node (more tests required).

**Comment by Zonz** [comment]
Fixed. Thanks!
