### ISSUE TITLE
Submap not found | Victory Road Kanto 3F

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#14]
**[Problem]**
Unsure - never encountered it before in that region. When using pathfinder.moveTo("Victory Road Kanto 3F") following exception was thrown once from that map itself:

> [02:20:04] Error during the script execution: pathfinder/Lib/MoveTo/MoveTo.lua:(186,9-124): Pathfinder --> sub map could not be defined, map: Victory Road Kanto 3F  x: 46  y: 13

_(I fixed it by restarting the script)_

In regards to issue #7, was this a global fix or are those map specific problems?

**Comment by Zonz** [comment]
These are map specific problems. The substitute maps had erroneous values.

This too has been fixed. Thanks!

**Comment by M1L4** [comment]
Ok, in that case I keep posting them :)
