### ISSUE TITLE
Submap doesn't exist | Route 14

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#15]
While on **Route 14**, calling *pf.useNearestPokecenter()*, following exception occured:
> [16:57:47] Error during the script execution: Pathfinder/Lib/MoveTo/MoveTo.lua:(86,10-115): Pathfinder --> Received node "Route 1B_B" doesn't exist in the map.

Destination should therefore be: "Pokecenter Fuchsia"

**Comment by Zonz** [comment]
Fixed. Thanks!
