### ISSUE TITLE
Reset and Recalc | Route 11 to Route 11 Stop House

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#18]
**[Problem]**
Cannot move from Route 11 to Route 11 Stop House.

**[Description]**
Path was from Vermillion to Route 11, where bot stopped and printed *Reset and Recalc* Exception:
> [22:35:23] Path: Maps Remains: 8  Moving To: --> Route 11 Stop House
> [22:35:23] Pathfinder --> Error in Path: from Route 11 to Route 11 Stop House -- Reset and Recalc

Moving the bot manually to Route 11 Stop House, solved the issue. The NPC from 10,12 seems unrelated, got the error with or without him.

**Comment by Zonz** [comment]
Fixed. Thanks!
