### ISSUE TITLE
Surf Required | Route 19 to 18

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#19]
**[Problem]**
Surf requirement when moving from Fuchsia Beach(Route 19) to Road West of Fuchsia (Route 18)

[Description]
This is moving to stop hous, fuchsia city, next route - there is no surf requirement at all. Seems like algorithm detected me on water:
> [23:07:41] Error during the script execution: pathfinder/Lib/MoveTo/MoveTo.lua:(339,21-97): Pathfinder --> Path Not Found ERROR. From Route 19 to Route 18_A | Route 18_B. A Pokemon with the move surf would open a path.

**Comment by Zonz** [comment]
Fixed. Thanks!
