### ISSUE TITLE
cant find route 17, 9 and 3

### ISSUE THREAD

**Issue by prouser1234** [Zonz/ProShinePathfinder#22]
`[19:20:46] Error during the script execution: Pathfinder/Lib/MoveTo/MoveTo.lua:(354,21-76): Pathfinder --> Path Not Found ERROR. From Route 15 to Route 17. Item: Bicycle would open a path.`

`[19:12:47] Path: Maps Remains: 2  Moving To: --> Route 9[19:12:47] Pathfinder --> Error in Path: from Cerulean City_A to Route 9 -- Reset and Recalc[19:12:48] Path: Cerulean City_A->Route 9->Route 10_B[19:12:48] Path: Maps Remains: 2  Moving To: --> Route 9[19:12:48] Pathfinder --> Error in Path: from Cerulean City_A to Route 9 -- Reset and Recalc[19:12:49] Path: Cerulean City_A->Route 9->Route 10_B[19:12:49] Path: Maps Remains: 2  Moving To: --> Route 9`

`[19:01:12] Path: Pewter City->Route 3[19:01:12] Path: Maps Remains: 1  Moving To: --> Route 3[19:01:12] Pathfinder --> Error in Path: from Pewter City to Route 3 -- Reset and Recalc[19:01:13] Path: Pewter City->Route 3`

while trying to use the script of 
name = "Dig, Headbutt and Discover"
author = "Programminghigh"
description = [[Dig, Headbutt and Discover]]

encountered those problems.

**Comment by Zonz** [comment]
The first issue is due to you not having a bicycle, hence the error.

The other issues have been fixed. Thanks for reporting!

**Comment by prouser1234** [comment]
i do have a bike using them to travel :O
@Zonz

**Comment by Zonz** [comment]
Apologies, this was due to Pathfinder not checking for the different bike color variants. It's fixed now. Hopefully.
