### ISSUE TITLE
Map Link Update | Rock Tunnel 1

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#28]
**[Problem]**
From Route 10 to Rock Tunnel: the map link name got changed from "Rock Tunnel 1" to "Link":

> [16:49:28] Pathfinder --> Error in Path: from Route 10_A to Rock Tunnel 1_A -- Reset and Recalc

**Comment by Zonz** [comment]
This was fixed last night. Get yourself a fresh version. ;)

**Comment by M1L4** [comment]
haha - alright, sry :D
