### ISSUE TITLE
Pathfinder.mapName()

### ISSUE THREAD

**Issue by DubsCheckum** [Zonz/ProShinePathfinder#32]
A `Pathfinder.mapName()` would be a nice addition.
When you call it, it would return the map name that the pathfinder recognizes, ie `Route 10_A`.

# **The problem**
**_Scenario:_** You start a script using pathfinder at the destination/farming map, `Route 10_C`, for example. The hunt type might be `moveToGrass()`, there's no grass in `Route 10_C`, but there _is_ in `Route 10_A`. No action executed. 

The script can't tell the difference because it's using 
`if getMapName() == "Route 10" then`
`moveToGrass()`

# **The solution**
With the added feature we could do
`if pf.mapName() == "Route 10_A" then`
`moveToGrass()`
and all of the world's problems would be solved.

**Comment by Zonz** [comment]
Done! Nice idea.
