### ISSUE TITLE
No alternative route | within map

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#6]
**No alternative Route** - Problem:
Pathfinder doesn't consider alternative routes within a map.

Example:
Pathfinder suggested a path passing Route, where Snorlax was blocking the way. The algorithm looped following exception, although I had a pkm with surf ability:
> Pathfinder --> Error in Path: from Route 12 to Lavender Town -- Reset and Recalc

This scenario can happen by either:
- trading pokemon with surf ability prior to "have to fight relaxo"-game state
- using blissey's scripts utilizing a "passing through blocked paths" glitch

Expected Behaviour:
Since the normal path on bridge was blocked, bot could have used surf move to avoid snorlax.

**Comment by Zonz** [comment]
Pathfinder does nothing special with moving through maps. All it does is call moveToMap with the next map name in the path, so surf not working is an issue with the bot itself, not with Pathfinder.

**Comment by M1L4** [comment]
yes indeed - see Issue #11 *Wrong Distance Calculation | split routing implementations*

Here some thoughts on why I think the issue lies within pathfinder and not proshine:
- The stated exception is thrown by pathfinder and doesn't originate from proshine:
> Pathfinder --> Error in Path: from Route 12 to Lavender Town -- Reset and Recalc
- proshine pathing utilises *surf* fluently, never had any problems with it before - so it seems unlikely (to me it feels like pathfinder forcfully abourts routing)
- Route 12 seems susceptible in particullar. I am unsure of how many pathfinders crashed at that route - it was alot :D *(this statement is a little more biased as the only non pathfinder script I am using is wiwi's questing)*
- regarding previous statement: assuming the problem is caused by proshine - shouldn't some complaints be present on proShine's side then? The problem shouldn't be tied to that location either...
- further assuming proShine causing the error: in that case pathfinder should:
  _ somehow point out error cause being proShine (debugging purposes)
  _ best case: compensate pathfinders fault (since pathfinder currently is the interface being used) - as far as I can tell: impossible in its current implementation
