### ISSUE TITLE
Submap not found | Seafoam B3F

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#7]
**[Problem]**
When using *pathfinder.moveTo("Seafoam B4F")* following exception is thrown on map Seafoam B3F:

> [20:46:35] Error during the script execution: pathfinder/Lib/MoveTo/MoveTo.lua:(186,9-124): Pathfinder --> sub map could not be defined, map: Seafoam B3F  x: 14  y: 13

**Comment by M1L4** [comment]
Another occasion:
> [22:29:23] Error during the script execution: pathfinder/Lib/MoveTo/MoveTo.lua:(186,9-124): Pathfinder --> sub map could not be defined, map: Seafoam B4F  x: 10  y: 12

**Comment by Zonz** [comment]
Fixed. Thanks!

**Comment by M1L4** [comment]
Wow - you're efficient xD
GJ :D
