### ISSUE TITLE
Black out | causes exception

### ISSUE THREAD

**Issue by M1L4** [Zonz/ProShinePathfinder#8]
**[Problem]**
It seems as if a current_map variable isn't updated when bot/character blacks out. 

**[Description]**
While farming in Seafoam B4F my bot blacked out and got teleported back to Cinnabar Pokecenter. It causes an exception and the bot is terminated:

> [21:06:49] You have no more usable Pokemon. 
> [21:06:49] You black out! 
> [21:06:49] Position updated: Pokecenter Cinnabar (9, 18) [WARNING, different map] /!\
> [21:06:54] Error during the script execution: pathfinder/Lib/MoveTo/MoveTo.lua:(161,8-142): Pathfinder --> Error: Exception invalid for: Seafoam B3F_E -> Seafoam B4F_B

**[Expected behaviour]**
When teleported because of feinting, the bot should move back to intended location.

**[Comment]**
There shouldn't be any problem with the routing, since getting to Seafoam B4F was also done via pathfidner and worked smoothly - even visiting cinnabar pokecenter >> exact same path

**Comment by Zonz** [comment]
I've attempted a fix for this. Please let me know if you still get it.

**Comment by M1L4** [comment]
It's a little difficult to reproduce, since I only gotten that error once. I will update you, when I have correlating data.

**Comment by M1L4** [comment]
Seems to be fixed - didn't encounter it for a while now :)
